create-diff-object: fix use after free in kpatch-check-relocations()
dynup/kpatch pull request #1211
Opened 2021-08-22 17:18 UTC by joe-lawrence

Building data-read-mostly.patch on rhel-9.0-beta for ppc64le leads to a
segmentation fault:

    Program received signal SIGSEGV, Segmentation fault.
    kpatch_check_relocations (kelf=0x10040490) at create-diff-object.c:2571
    2571                                    sdata = rela->sym->sec->data;
    (gdb) bt
    (gdb) p rela->sym->sec->data
    Cannot access memory at address 0x160000007e

Valgrind narrows the problem down to invalid reads through rela->sym in
kpatch-check-relocations().

The culprits are kpatch_create_intermediate_sections(), which marks
symbols referenced by rela sections that are now dynrelas to be
stripped, and kpatch_strip_unneeded_syms(), which removes and frees
them.

The problem with the symbol stripping is that multiple relas may
reference the same ELF symbol.  If any remaining relocation references a
shared symbol, we must keep it.

Replace the symbol->strip boolean with an enumeration:

  SYMBOL_DEFAULT - initial value, symbol usage unknown
  SYMBOL_USED    - symbol is definitely used by a rela
  SYMBOL_STRIP   - symbol was only referenced by dynrela(s)

Allow transitions from SYMBOL_DEFAULT to SYMBOL_* and SYMBOL_STRIP to
SYMBOL_USED, but _not_ SYMBOL_USED to SYMBOL_*.

Signed-off-by: Joe Lawrence <joe.lawrence@redhat.com>

2021-08-22 17:21 UTC, joe-lawrence commented
I added dbg printf's while debugginf this (see `kpatch-build.diff` in attached repro tarball):
```
$ ./repro &> repro.out

$ grep '^dbg:' repro.out | tail -n1
dbg: check symbol: section: .rela__jump_table, rela @ 0x100288f5d80 rela->sym @ 0x1002886b270

$ grep -e 0x1002886b270 -e 0x100288f5d80 repro.out 
dbg: section: .rela.toc, rela @ 0x100288e7f80 rela->sym @ 0x1002886b270 netstamp_needed_key
dbg: section: .rela__jump_table, rela @ 0x100288f5d80 rela->sym @ 0x1002886b270 netstamp_needed_key
dbg: strip symbol: section: .rela.toc, rela @ 0x100288e7f80 rela->sym @ 0x1002886b270 netstamp_needed_key
dbg: free stripped sym @ 0x1002886b270 netstamp_needed_key
dbg: check symbol: section: .rela__jump_table, rela @ 0x100288f5d80 rela->sym @ 0x1002886b270
```
and can see that the problem is that the symbol for `netstamp_needed_key` was used after it was freed.

I encountered a bug like this in upstream klp-convert development (see https://github.com/joe-lawrence/linux/commit/e2ec7b6117aa517b5280db67727ef2dd85d04001 for example), where multiple relocation symbols are share the same symbol.  One must be careful when throwing away such shared symbols.

Comments welcome.  An alternative approach I considered was some kind of rela<->symbol reference count, but thought that might be overkill.

[repro.tar.gz](https://github.com/dynup/kpatch/files/7027440/repro.tar.gz)

2021-08-23 14:29 UTC, sm00th commented
Looks ok, but the objectfiles from the repro tarball are prime candidates for addition to unit tests.

2021-08-23 15:45 UTC, joe-lawrence commented
> Looks ok, but the objectfiles from the repro tarball are prime candidates for addition to unit tests.

Good idea.  I'm a bit surprised we haven't seen this in real world CVE kpatches.. but it took a long while to encounter it in klp-convert work, so perhaps just another weird corner case.  I'll prep a unit test PR later.  In the meantime, do you think the enum in kpatch-elf.h needs a description of its intent?  Or any other comments to clarify the code if you think it may hide some subtlety.

2021-08-23 16:08 UTC, sm00th commented
> In the meantime, do you think the enum in kpatch-elf.h needs a description of its intent? Or any other comments to clarify the code if you think it may hide some subtlety.

The commit message is good enough for me personally, but if you worry about intent being clear I think we can leave sym->strip as boolean and just make `SYMBOL_USED` a local flag in that `list_for_each_entry_safe` loop.

2021-08-23 16:26 UTC, joe-lawrence commented
> > In the meantime, do you think the enum in kpatch-elf.h needs a description of its intent? Or any other comments to clarify the code if you think it may hide some subtlety.
> 
> The commit message is good enough for me personally, but if you worry about intent being clear I think we can leave sym->strip as boolean and just make `SYMBOL_USED` a local flag in that `list_for_each_entry_safe` loop.

Would that be saved into another field or list somehow?

I'm stuck on how to keep a boolean value that represents three ideas:

1. initial condition, okay to set to any value
2. definitely used, can't strip it
3. may be unused, suitable to strip for now

so an additional flag could help, but how would that work?

2021-08-23 16:31 UTC, sm00th commented
> so an additional flag could help, but how would that work?

You are right, it won't, nvm

2021-09-08 09:07 UTC, sm00th requested changes
Requires unit-tests added so marking as such.

2021-09-15 02:56 UTC, joe-lawrence commented
(updated with unit test objects subproject update)

2021-09-15 05:07 UTC, kamalesh-babulal approved these changes

2021-09-15 08:25 UTC, sm00th approved these changes

2021-09-15 14:31 UTC, merged