kpatch-build: support Photon OS distribution
dynup/kpatch pull request #1339
Opened 2023-04-14 18:51 UTC by bhllamoreaux

VMware's Photon OS uses kpatch to build and load kernel livepatches, starting with 3.0.
Ref: https://github.com/vmware/photon/tree/master/SPECS/kpatch

It would be nice to have support for Photon OS in kpatch-build, so that kpatch-build works for
Photon out of the box. Ideally, this will work the same as for other supported distros,  where
kpatch-build can be invoked just as:
     `kpatch-build <name>.patch.`

This commit handles setup of all kernel sources, vmlinux files, etc for Photon OS.

cc @sshedi

2023-04-14 21:04 UTC, jpoimboe commented
@bhllamoreaux thanks for the contribution!

The code is doing several of the same things the Fedora/RHEL/OL/CentOS/openEuler code is doing, yet in an a slightly different way, making it harder to review.  Since Photon OS is RPM-based, I would much rather try to converge it with the `if [[ "$DISTRO" = fedora ]]...` code.

I know there are some inherent differences between the distros, but even if there have to be several Photon OS checks within, that would still make it much easier to review for correctness, i.e. that all the right variables are being set and that the printouts are consistent between distributions.  And it would also make it easier to spot the commonalities and differences between the distros if we want to refactor the code later.

2023-04-14 22:29 UTC, bhllamoreaux commented
Thanks for the quick response! That sounds reasonable, I'll give it a shot.

2023-04-20 20:34 UTC, bhllamoreaux commented
Updated the changes to be integrated into the existing code, instead of in a Photon specific section, as suggested.

2023-04-24 13:50 UTC, sshedi requested changes
Good work @bhllamoreaux. Some minor tweaks needed.

2023-04-24 13:50 UTC, sshedi commented on kpatch-build/kpatch-build
> -			SRCRPM="$TEMPDIR/kernel$ALT-$KVER-$KREL.src.rpm"
```
if [ -z "$SRCRPM" ]; then
  SRCRPM="$TEMPDIR/kernel$ALT-$KVER-$KREL.src.rpm"
fi
```
And remove it from line 921 & 935

2023-04-24 13:50 UTC, sshedi commented on kpatch-build/kpatch-build
> +				wget -P "$TEMPDIR" "https://packages.vmware.com/photon/$PHOTON_VERSION/photon_srpms_${PHOTON_VERSION}_x86_64/$SRC_RPM_NAME" 2>&1 | logger || die
_x86_64 --> $(uname -m)
we might support aarch64 someday

2023-04-24 13:50 UTC, sshedi commented on test/integration/lib.sh
> +		make gcc elfutils elfutils-devel systemd-rpm-macros build-essential
nit:
`build-essentail` implicitly brings in `gcc, make, gawk, binutils`
`elfutils-devel` brings in `elfutils` so we can remove the redundant entries from here

2023-04-24 23:07 UTC, bhllamoreaux commented
Updated with suggested tweaks

2023-05-04 09:44 UTC, sshedi commented
Hi @jpoimboe can you please take a look again. Thanks.

2023-05-12 03:50 UTC, jpoimboe reviewed
Looking good!  I added a few minor comments

2023-05-12 03:50 UTC, jpoimboe commented on kpatch-build/kpatch-build
> +if [[ "$DISTRO" = fedora ]] || [[ "$DISTRO" = rhel ]] || [[ "$DISTRO" = ol ]] || [[ "$DISTRO" = centos ]] || [[ "$DISTRO" = openEuler ]] || [[ "$DISTRO" = photon ]]; then
Can we split this in two lines?
```
if [[ "$DISTRO" = fedora ]] || [[ "$DISTRO" = rhel ]] || [[ "$DISTRO" = ol ]] ||
   [[ "$DISTRO" = centos ]] || [[ "$DISTRO" = openEuler ]] ||
   [[ "$DISTRO" = photon ]]; then

	[[ -z "$VMLINUX" ]] && VMLINUX="/usr/lib/debug/lib/modules/$ARCHVERSION/vmlinux"
```

2023-05-12 03:50 UTC, jpoimboe commented on kpatch-build/kpatch-build
> +				sed -i s/^CONFIG_LOCALVERSION=\".*\"/CONFIG_LOCALVERSION=\"-"$KREL"."$PH_TAG"-"$PH_FLAVOR"\"/g "$CONFIGFILE"
These should have `|| die`

2023-06-06 17:35 UTC, bhllamoreaux commented
Apologies for the delay, I was distracted with some other work for a bit. Hopefully the latest revision looks good

2023-06-06 22:02 UTC, jpoimboe approved these changes

2023-06-20 14:29 UTC, sshedi commented
@jpoimboe can we merge this PR? Been pending from a while now. Thanks.

2023-06-20 18:00 UTC, jpoimboe commented
@joe-lawrence does this look ok to you?

2023-06-20 21:11 UTC, joe-lawrence approved these changes

2023-06-20 21:12 UTC, joe-lawrence commented
> @joe-lawrence does this look ok to you?

:+1:

2023-06-21 00:01 UTC, merged

2023-06-21 05:09 UTC, sshedi commented
Thanks a lot for your time and inputs @joe-lawrence and @jpoimboe.

Have a nice time ahead.

2023-06-21 06:36 UTC, bhllamoreaux commented
^^ Thanks everyone @jpoimboe @sshedi @joe-lawrence